(function (global) {
  "use strict";
  const PRIORITY_RANK = { urgent: 4, high: 3, medium: 2, low: 1 };
  const VIEW_LABELS = { all: "全部任务", active: "进行中", completed: "已完成", today: "今日到期", overdue: "已逾期", archived: "归档", scheduled: "重复任务" };
  const REPEAT_OPTIONS = ["none", "daily", "weekly", "monthly"];
  const TAG_PALETTE = [
    { bg: "rgba(109, 124, 255, 0.18)", border: "rgba(109, 124, 255, 0.42)", text: "#c7d2fe" },
    { bg: "rgba(34, 211, 238, 0.16)", border: "rgba(34, 211, 238, 0.4)", text: "#a5f3fc" },
    { bg: "rgba(52, 211, 153, 0.16)", border: "rgba(52, 211, 153, 0.4)", text: "#a7f3d0" },
    { bg: "rgba(251, 191, 36, 0.16)", border: "rgba(251, 191, 36, 0.42)", text: "#fde68a" },
    { bg: "rgba(251, 113, 133, 0.16)", border: "rgba(251, 113, 133, 0.42)", text: "#fecdd3" },
    { bg: "rgba(167, 139, 250, 0.16)", border: "rgba(167, 139, 250, 0.42)", text: "#ddd6fe" },
    { bg: "rgba(56, 189, 248, 0.16)", border: "rgba(56, 189, 248, 0.4)", text: "#bae6fd" },
    { bg: "rgba(244, 114, 182, 0.16)", border: "rgba(244, 114, 182, 0.4)", text: "#fbcfe8" }
  ];
  function createId(){ if(global.crypto&&typeof global.crypto.randomUUID==="function") return global.crypto.randomUUID(); return "id-"+Date.now()+"-"+Math.random().toString(16).slice(2); }
  function todayKey(date){ const d=date?new Date(date):new Date(); return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0"); }
  function uniqueTags(tags){ const seen=new Set(); const result=[]; (tags||[]).forEach(function(tag){ const cleaned=String(tag||"").trim().replace(/\s+/g," "); if(!cleaned) return; const key=cleaned.toLowerCase(); if(seen.has(key)) return; seen.add(key); result.push(cleaned); }); return result.slice(0,12); }
  function normalizeTags(input){ if(Array.isArray(input)) return uniqueTags(input); if(typeof input!=="string") return []; return uniqueTags(input.split(/[,，]/).map(function(tag){return tag.trim();}).filter(Boolean)); }
  function hashString(input){ let hash=0; const text=String(input||""); for(let i=0;i<text.length;i+=1){ hash=((hash<<5)-hash)+text.charCodeAt(i); hash|=0; } return Math.abs(hash); }
  function tagColor(name){ return TAG_PALETTE[hashString(String(name||"").toLowerCase())%TAG_PALETTE.length]; }
  function normalizePriority(value){ if(value==="low"||value==="high"||value==="urgent") return value; return "medium"; }
  function normalizeRepeat(value){ return REPEAT_OPTIONS.indexOf(value)>=0?value:"none"; }
  function normalizeRemindTime(value){ if(typeof value==="string"&&/^\d{2}:\d{2}$/.test(value)) return value; return "09:00"; }
  function addDays(dateStr,days){ const d=new Date(dateStr+"T00:00:00"); d.setDate(d.getDate()+days); return todayKey(d); }
  function addMonths(dateStr,months){ const d=new Date(dateStr+"T00:00:00"); const day=d.getDate(); d.setMonth(d.getMonth()+months); if(d.getDate()<day) d.setDate(0); return todayKey(d); }
  function nextDueDate(dueDate,repeat){ const base=dueDate&&/^\d{4}-\d{2}-\d{2}$/.test(dueDate)?dueDate:todayKey(); if(repeat==="daily") return addDays(base,1); if(repeat==="weekly") return addDays(base,7); if(repeat==="monthly") return addMonths(base,1); return null; }
  function defaultLists(){ const now=Date.now(); return [{id:"list-inbox",name:"收件箱",icon:"📥",order:1,createdAt:now},{id:"list-work",name:"工作",icon:"💼",order:2,createdAt:now+1},{id:"list-life",name:"生活",icon:"🏠",order:3,createdAt:now+2}]; }
  function normalizeList(raw,index){ const now=Date.now(); const name=String((raw&&raw.name)||"").trim()||"未命名清单"; return {id:raw&&typeof raw.id==="string"&&raw.id?raw.id:createId(),name:name.slice(0,20),icon:String((raw&&raw.icon)||"📁").slice(0,4)||"📁",order:typeof (raw&&raw.order)==="number"?raw.order:(index+1)*1000,createdAt:typeof (raw&&raw.createdAt)==="number"?raw.createdAt:now}; }
  function normalizeTodo(raw,index,fallbackListId){ const now=Date.now(); const text=String((raw&&raw.text)||"").trim(); return {id:raw&&typeof raw.id==="string"&&raw.id?raw.id:createId(),text:text,notes:String((raw&&raw.notes)||"").trim(),completed:!!(raw&&raw.completed),archived:!!(raw&&raw.archived),priority:normalizePriority(raw&&raw.priority),dueDate:raw&&typeof raw.dueDate==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(raw.dueDate)?raw.dueDate:null,tags:normalizeTags(raw&&raw.tags),listId:raw&&typeof raw.listId==="string"&&raw.listId?raw.listId:(fallbackListId||"list-inbox"),repeat:normalizeRepeat(raw&&raw.repeat),remindEnabled:!!(raw&&raw.remindEnabled),remindTime:normalizeRemindTime(raw&&raw.remindTime),lastNotifiedKey:raw&&typeof raw.lastNotifiedKey==="string"?raw.lastNotifiedKey:null,completedAt:typeof (raw&&raw.completedAt)==="number"?raw.completedAt:null,order:typeof (raw&&raw.order)==="number"?raw.order:index||now,createdAt:typeof (raw&&raw.createdAt)==="number"?raw.createdAt:now,updatedAt:typeof (raw&&raw.updatedAt)==="number"?raw.updatedAt:now}; }
  function defaultSettings(){ return {theme:"dark",view:"all",sort:"manual",search:"",activeTag:"",activeListId:"all",notificationsEnabled:false}; }

  function createStore(db){
    const state={todos:[],lists:defaultLists(),settings:defaultSettings(),tagLibrary:[],ready:false};
    const listeners=new Set();
    let reminderTimer=null;
    function emit(){ listeners.forEach(function(fn){ try{fn(getSnapshot());}catch(error){console.error(error);} }); }
    function getSnapshot(){ return {todos:state.todos.slice(),lists:state.lists.slice().sort(function(a,b){return a.order-b.order;}),settings:Object.assign({},state.settings),tagLibrary:state.tagLibrary.slice(),ready:state.ready,counts:getCounts(),listCounts:getListCounts(),tags:getTagStats(),managedTags:getManagedTags(),stats:getStats(),focusTodos:getFocusTodos(),visibleTodos:getVisibleTodos(),upcomingReminders:getUpcomingReminders()}; }
    function subscribe(fn){ listeners.add(fn); return function(){ listeners.delete(fn); }; }
    function listExists(id){ return state.lists.some(function(list){return list.id===id;}); }
    function ensureListId(listId){ if(listId&&listExists(listId)) return listId; return state.lists[0]?state.lists[0].id:"list-inbox"; }
    function getCounts(){ const activeListId=state.settings.activeListId||"all"; const inList=function(todo){return activeListId==="all"||todo.listId===activeListId;}; const base=state.todos.filter(function(todo){return !todo.archived&&inList(todo);}); const archived=state.todos.filter(function(todo){return todo.archived&&inList(todo);}); const today=todayKey(); return {all:base.length,active:base.filter(function(todo){return !todo.completed;}).length,completed:base.filter(function(todo){return todo.completed;}).length,today:base.filter(function(todo){return !todo.completed&&todo.dueDate===today;}).length,overdue:base.filter(function(todo){return !todo.completed&&todo.dueDate&&todo.dueDate<today;}).length,archived:archived.length,scheduled:base.filter(function(todo){return !todo.completed&&todo.repeat&&todo.repeat!=="none";}).length}; }
    function getListCounts(){ const map={}; state.lists.forEach(function(list){map[list.id]=0;}); state.todos.forEach(function(todo){ if(todo.archived||todo.completed) return; if(map[todo.listId]==null) map[todo.listId]=0; map[todo.listId]+=1; }); return map; }
    function getUsageMap(){ const map=new Map(); state.todos.forEach(function(todo){ (todo.tags||[]).forEach(function(tag){ map.set(tag,(map.get(tag)||0)+1); }); }); return map; }
    function getTagStats(){ const map=new Map(); state.todos.forEach(function(todo){ if(todo.archived) return; todo.tags.forEach(function(tag){ map.set(tag,(map.get(tag)||0)+1); }); }); state.tagLibrary.forEach(function(tag){ if(!map.has(tag)) map.set(tag,0); }); return Array.from(map.entries()).map(function(entry){ return {name:entry[0],count:entry[1],color:tagColor(entry[0])}; }).sort(function(a,b){ return b.count-a.count||a.name.localeCompare(b.name,"zh-CN"); }); }
    function getManagedTags(){ const usage=getUsageMap(); const names=uniqueTags(state.tagLibrary.concat(Array.from(usage.keys()))); return names.map(function(name){ return {name:name,count:usage.get(name)||0,inLibrary:state.tagLibrary.some(function(tag){return tag.toLowerCase()===name.toLowerCase();}),color:tagColor(name)}; }).sort(function(a,b){ return a.name.localeCompare(b.name,"zh-CN"); }); }
    async function persistTagLibrary(){ await db.setMeta("tagLibrary", state.tagLibrary); }
    async function persistLists(){ await db.setMeta("lists", state.lists); }
    async function persistSettings(){ await db.setMeta("settings", state.settings); }
    async function persistTodo(todo){ await db.putTodo(todo); }
    function ensureTagsInLibrary(tags){ const incoming=normalizeTags(tags); if(!incoming.length) return false; const existing=new Set(state.tagLibrary.map(function(tag){return tag.toLowerCase();})); let changed=false; incoming.forEach(function(tag){ if(!existing.has(tag.toLowerCase())){ state.tagLibrary.push(tag); existing.add(tag.toLowerCase()); changed=true; } }); if(changed) state.tagLibrary=uniqueTags(state.tagLibrary).sort(function(a,b){return a.localeCompare(b,"zh-CN");}); return changed; }
    function getStats(){ const activeListId=state.settings.activeListId||"all"; const live=state.todos.filter(function(todo){ return !todo.archived&&(activeListId==="all"||todo.listId===activeListId); }); const total=live.length; const completed=live.filter(function(todo){return todo.completed;}).length; const high=live.filter(function(todo){return !todo.completed&&(todo.priority==="high"||todo.priority==="urgent");}).length; const today=todayKey(); const dueSoon=live.filter(function(todo){ if(todo.completed||!todo.dueDate) return false; const diff=(new Date(todo.dueDate+"T00:00:00")-new Date(today+"T00:00:00"))/86400000; return diff>=0&&diff<=3; }).length; const repeating=live.filter(function(todo){return !todo.completed&&todo.repeat&&todo.repeat!=="none";}).length; return {completion:total?Math.round((completed/total)*100):0,high:high,dueSoon:dueSoon,repeating:repeating}; }
    function getFocusTodos(){ const today=todayKey(); const activeListId=state.settings.activeListId||"all"; return state.todos.filter(function(todo){ if(todo.archived||todo.completed) return false; if(activeListId!=="all"&&todo.listId!==activeListId) return false; const isOverdue=!!todo.dueDate&&todo.dueDate<today; const isToday=todo.dueDate===today; const isHot=todo.priority==="urgent"||todo.priority==="high"; const isRemindToday=todo.remindEnabled&&todo.dueDate===today; return isOverdue||isToday||isHot||isRemindToday; }).sort(function(a,b){ const aOverdue=a.dueDate&&a.dueDate<today?0:1; const bOverdue=b.dueDate&&b.dueDate<today?0:1; if(aOverdue!==bOverdue) return aOverdue-bOverdue; const aToday=a.dueDate===today?0:1; const bToday=b.dueDate===today?0:1; if(aToday!==bToday) return aToday-bToday; const pr=(PRIORITY_RANK[b.priority]||0)-(PRIORITY_RANK[a.priority]||0); if(pr) return pr; if(a.dueDate&&b.dueDate) return a.dueDate.localeCompare(b.dueDate); if(a.dueDate) return -1; if(b.dueDate) return 1; return a.order-b.order; }).slice(0,5); }
    function matchesView(todo,view){ const today=todayKey(); if(view==="archived") return todo.archived; if(todo.archived) return false; if(view==="active") return !todo.completed; if(view==="completed") return todo.completed; if(view==="today") return !todo.completed&&todo.dueDate===today; if(view==="overdue") return !todo.completed&&!!todo.dueDate&&todo.dueDate<today; if(view==="scheduled") return !todo.completed&&todo.repeat&&todo.repeat!=="none"; return true; }
    function sortTodos(list,sort){ const cloned=list.slice(); if(sort==="created_desc") return cloned.sort(function(a,b){return b.createdAt-a.createdAt;}); if(sort==="due_asc") return cloned.sort(function(a,b){ if(!a.dueDate&&!b.dueDate) return a.order-b.order; if(!a.dueDate) return 1; if(!b.dueDate) return -1; return a.dueDate.localeCompare(b.dueDate)||a.order-b.order; }); if(sort==="priority_desc") return cloned.sort(function(a,b){ return (PRIORITY_RANK[b.priority]||0)-(PRIORITY_RANK[a.priority]||0)||a.order-b.order; }); if(sort==="alpha_asc") return cloned.sort(function(a,b){ return a.text.localeCompare(b.text,"zh-CN")||a.order-b.order; }); return cloned.sort(function(a,b){return a.order-b.order;}); }
    function getVisibleTodos(){ const settings=state.settings; const keyword=(settings.search||"").trim().toLowerCase(); const activeListId=settings.activeListId||"all"; let list=state.todos.filter(function(todo){ if(activeListId!=="all"&&todo.listId!==activeListId) return false; if(!matchesView(todo,settings.view)) return false; if(settings.activeTag&&todo.tags.map(function(tag){return tag.toLowerCase();}).indexOf(settings.activeTag.toLowerCase())===-1) return false; if(!keyword) return true; const listName=(state.lists.find(function(item){return item.id===todo.listId;})||{}).name||""; const hay=[todo.text,todo.notes,listName].concat(todo.tags).join(" ").toLowerCase(); return hay.indexOf(keyword)!==-1; }); return sortTodos(list,settings.sort); }
    function getUpcomingReminders(){ const today=todayKey(); return state.todos.filter(function(todo){ return !todo.archived&&!todo.completed&&todo.remindEnabled&&todo.dueDate&&todo.dueDate<=today; }).slice(0,10); }
    function reminderDueNow(todo,now){ if(!todo.remindEnabled||todo.completed||todo.archived||!todo.dueDate) return false; const today=todayKey(now); if(todo.dueDate>today) return false; const parts=(todo.remindTime||"09:00").split(":"); const hh=parseInt(parts[0],10)||9; const mm=parseInt(parts[1],10)||0; const fire=new Date(todo.dueDate+"T00:00:00"); fire.setHours(hh,mm,0,0); if(now.getTime()<fire.getTime()&&todo.dueDate===today) return false; const key=todo.dueDate+"@"+(todo.remindTime||"09:00"); return todo.lastNotifiedKey!==key; }
    async function markNotified(todo,key){ return updateTodo(todo.id,{lastNotifiedKey:key}); }
    async function checkReminders(notifier){ if(!state.settings.notificationsEnabled) return []; const now=new Date(); const due=state.todos.filter(function(todo){return reminderDueNow(todo,now);}); const fired=[]; for(const todo of due){ const key=todo.dueDate+"@"+(todo.remindTime||"09:00"); if(typeof notifier==="function"){ try{notifier(todo);}catch(error){console.warn(error);} } await markNotified(todo,key); fired.push(todo); } return fired; }
    function startReminderLoop(notifier){ stopReminderLoop(); reminderTimer=global.setInterval(function(){ checkReminders(notifier); },30000); checkReminders(notifier); }
    function stopReminderLoop(){ if(reminderTimer){ global.clearInterval(reminderTimer); reminderTimer=null; } }

    async function init(){
      const [todos,settings,lists,tagLibrary]=await Promise.all([db.getAllTodos(),db.getMeta("settings",defaultSettings()),db.getMeta("lists",null),db.getMeta("tagLibrary",null)]);
      if(Array.isArray(lists)&&lists.length){ state.lists=lists.map(function(item,index){return normalizeList(item,index);}); }
      else { state.lists=defaultLists(); await persistLists(); }
      let migrated=false;
      try{
        const legacyRaw=global.localStorage.getItem("todo-app.v1");
        if(legacyRaw&&(!todos||!todos.length)){
          const legacy=JSON.parse(legacyRaw);
          if(legacy&&Array.isArray(legacy.todos)&&legacy.todos.length){
            state.todos=legacy.todos.map(function(item,index){ return normalizeTodo({id:item.id,text:item.text,completed:item.completed,createdAt:item.createdAt,updatedAt:item.createdAt,order:item.createdAt||index,listId:state.lists[0].id},index,state.lists[0].id); });
            await db.putTodos(state.todos); migrated=true;
          }
        }
      }catch(error){ console.warn("legacy migration skipped", error); }
      if(!migrated){
        state.todos=(todos||[]).map(function(item,index){ return normalizeTodo(item,index,state.lists[0].id); });
        let repaired=false;
        state.todos=state.todos.map(function(todo){ if(!listExists(todo.listId)){ repaired=true; return Object.assign({},todo,{listId:state.lists[0].id}); } return todo; });
        if(repaired) await db.putTodos(state.todos);
      }
      state.settings=Object.assign(defaultSettings(),settings||{});
      if(!VIEW_LABELS[state.settings.view]) state.settings.view="all";
      if(state.settings.activeListId!=="all"&&!listExists(state.settings.activeListId)) state.settings.activeListId="all";
      if(Array.isArray(tagLibrary)&&tagLibrary.length){ state.tagLibrary=uniqueTags(tagLibrary); }
      else {
        const used=[]; state.todos.forEach(function(todo){ (todo.tags||[]).forEach(function(tag){ used.push(tag); }); });
        state.tagLibrary=uniqueTags(used.concat(["工作","设计","本周","生活","学习"]));
        await persistTagLibrary();
      }
      state.ready=true; emit(); return getSnapshot();
    }
    async function addTodo(input){
      const text=String((input&&input.text)||"").trim(); if(!text) return {ok:false,error:"请输入待办内容，空内容不能添加。"};
      const now=Date.now(); const minOrder=state.todos.reduce(function(min,todo){return Math.min(min,todo.order);},now);
      const preferredList=input&&input.listId?input.listId:(state.settings.activeListId!=="all"?state.settings.activeListId:state.lists[0].id);
      const todo=normalizeTodo({text:text,notes:input&&input.notes,priority:input&&input.priority,dueDate:input&&input.dueDate,tags:input&&input.tags,listId:ensureListId(preferredList),repeat:input&&input.repeat,remindEnabled:input&&input.remindEnabled,remindTime:input&&input.remindTime,completed:false,archived:false,order:minOrder-1,createdAt:now,updatedAt:now},0,state.lists[0].id);
      state.todos.unshift(todo); const libraryChanged=ensureTagsInLibrary(todo.tags); await persistTodo(todo); if(libraryChanged) await persistTagLibrary(); emit(); return {ok:true,todo:todo};
    }
    async function updateTodo(id,patch){
      const index=state.todos.findIndex(function(todo){return todo.id===id;}); if(index===-1) return {ok:false,error:"任务不存在。"};
      const current=state.todos[index];
      const merged=Object.assign({},current,patch,{id:current.id,createdAt:current.createdAt,updatedAt:Date.now()});
      if(patch&&Object.prototype.hasOwnProperty.call(patch,"listId")) merged.listId=ensureListId(patch.listId);
      if(patch&&Object.prototype.hasOwnProperty.call(patch,"completed")) merged.completedAt=patch.completed?(current.completedAt||Date.now()):null;
      const next=normalizeTodo(merged,current.order,state.lists[0].id); if(!next.text) return {ok:false,error:"标题不能为空。"};
      state.todos[index]=next; const libraryChanged=ensureTagsInLibrary(next.tags); await persistTodo(next); if(libraryChanged) await persistTagLibrary(); emit(); return {ok:true,todo:next};
    }
    async function toggleTodo(id){
      const target=state.todos.find(function(todo){return todo.id===id;}); if(!target) return {ok:false};
      if(!target.completed&&target.repeat&&target.repeat!=="none"){
        const completed=await updateTodo(id,{completed:true,completedAt:Date.now()});
        const nextDue=nextDueDate(target.dueDate,target.repeat);
        const spawned=await addTodo({text:target.text,notes:target.notes,priority:target.priority,dueDate:nextDue,tags:target.tags,listId:target.listId,repeat:target.repeat,remindEnabled:target.remindEnabled,remindTime:target.remindTime});
        return {ok:true,todo:completed.todo,spawned:spawned.todo,repeated:true};
      }
      return updateTodo(id,{completed:!target.completed});
    }
    async function deleteTodo(id){ state.todos=state.todos.filter(function(todo){return todo.id!==id;}); await db.deleteTodo(id); emit(); return {ok:true}; }
    async function archiveTodo(id,archived){ if(archived) return updateTodo(id,{archived:true,completed:true}); return updateTodo(id,{archived:false}); }
    async function clearCompleted(){ const activeListId=state.settings.activeListId||"all"; const victims=state.todos.filter(function(todo){ return todo.completed&&!todo.archived&&(activeListId==="all"||todo.listId===activeListId); }); for(const todo of victims) await db.deleteTodo(todo.id); const victimIds=new Set(victims.map(function(todo){return todo.id;})); state.todos=state.todos.filter(function(todo){return !victimIds.has(todo.id);}); emit(); return {ok:true,removed:victims.length}; }
    async function setSettings(patch){ state.settings=Object.assign({},state.settings,patch); if(state.settings.activeListId!=="all"&&!listExists(state.settings.activeListId)) state.settings.activeListId="all"; await persistSettings(); emit(); return state.settings; }
    async function createList(input){ const name=String((input&&input.name)||"").trim(); if(!name) return {ok:false,error:"请输入清单名称。"}; if(state.lists.some(function(list){return list.name.toLowerCase()===name.toLowerCase();})) return {ok:false,error:"清单已存在。"}; const maxOrder=state.lists.reduce(function(max,list){return Math.max(max,list.order);},0); const list=normalizeList({name:name,icon:(input&&input.icon)||"📁",order:maxOrder+1000},state.lists.length); state.lists.push(list); await persistLists(); emit(); return {ok:true,list:list}; }
    async function renameList(id,name,icon){ const index=state.lists.findIndex(function(list){return list.id===id;}); if(index===-1) return {ok:false,error:"清单不存在。"}; const nextName=String(name||"").trim(); if(!nextName) return {ok:false,error:"清单名称不能为空。"}; state.lists[index]=normalizeList(Object.assign({},state.lists[index],{name:nextName,icon:icon||state.lists[index].icon}),index); await persistLists(); emit(); return {ok:true,list:state.lists[index]}; }
    async function deleteList(id){ if(state.lists.length<=1) return {ok:false,error:"至少保留一个清单。"}; const target=state.lists.find(function(list){return list.id===id;}); if(!target) return {ok:false,error:"清单不存在。"}; const fallback=state.lists.find(function(list){return list.id!==id;}); state.lists=state.lists.filter(function(list){return list.id!==id;}); let changed=false; state.todos=state.todos.map(function(todo){ if(todo.listId!==id) return todo; changed=true; return Object.assign({},todo,{listId:fallback.id,updatedAt:Date.now()}); }); if(state.settings.activeListId===id){ state.settings.activeListId="all"; await persistSettings(); } await persistLists(); if(changed) await db.putTodos(state.todos); emit(); return {ok:true,movedTo:fallback.id}; }
    async function reorderVisible(fromId,toId){ if(state.settings.sort!=="manual") return {ok:false,error:"当前不是手动排序模式。"}; const visible=getVisibleTodos(); const fromIndex=visible.findIndex(function(todo){return todo.id===fromId;}); const toIndex=visible.findIndex(function(todo){return todo.id===toId;}); if(fromIndex<0||toIndex<0||fromIndex===toIndex) return {ok:false}; const moving=visible[fromIndex]; const reordered=visible.slice(); reordered.splice(fromIndex,1); reordered.splice(toIndex,0,moving); const orderedIds=reordered.map(function(todo){return todo.id;}); const orderMap=new Map(); orderedIds.forEach(function(id,index){orderMap.set(id,(index+1)*1000);}); const rest=state.todos.filter(function(todo){return !orderMap.has(todo.id);}).sort(function(a,b){return a.order-b.order;}); rest.forEach(function(todo,index){orderMap.set(todo.id,(orderedIds.length+index+1)*1000);}); const now=Date.now(); state.todos=state.todos.map(function(todo){ return Object.assign({},todo,{order:orderMap.get(todo.id),updatedAt:now}); }); await db.putTodos(state.todos); emit(); return {ok:true}; }
    async function exportData(){ const data=await db.exportAll(); data.version=2; data.tagLibrary=state.tagLibrary.slice(); data.lists=state.lists.slice(); return data; }
    async function importData(payload,mode){ const todos=Array.isArray(payload&&payload.todos)?payload.todos.map(function(item,index){return normalizeTodo(item,index,"list-inbox");}).filter(function(item){return !!item.text;}):[]; if(Array.isArray(payload&&payload.lists)&&payload.lists.length){ state.lists=payload.lists.map(function(item,index){return normalizeList(item,index);}); } else if(mode==="replace"){ state.lists=defaultLists(); } await persistLists(); await db.importAll({todos:todos,settings:payload&&payload.settings?Object.assign(defaultSettings(),payload.settings):state.settings},mode||"merge"); state.todos=await db.getAllTodos().then(function(rows){ return (rows||[]).map(function(item,index){return normalizeTodo(item,index,state.lists[0].id);}); }); state.settings=Object.assign(defaultSettings(),await db.getMeta("settings",state.settings)); if(Array.isArray(payload&&payload.tagLibrary)){ state.tagLibrary=uniqueTags(payload.tagLibrary); } else { const used=[]; state.todos.forEach(function(todo){ (todo.tags||[]).forEach(function(tag){used.push(tag);}); }); state.tagLibrary=uniqueTags(state.tagLibrary.concat(used)); } await persistTagLibrary(); emit(); return {ok:true,count:todos.length}; }
    async function createTag(name){ const tags=normalizeTags(name); if(!tags.length) return {ok:false,error:"请输入标签名。"}; const tag=tags[0]; if(state.tagLibrary.some(function(item){return item.toLowerCase()===tag.toLowerCase();})) return {ok:false,error:"标签已存在。",tag:tag}; state.tagLibrary.push(tag); state.tagLibrary=uniqueTags(state.tagLibrary).sort(function(a,b){return a.localeCompare(b,"zh-CN");}); await persistTagLibrary(); emit(); return {ok:true,tag:tag}; }
    async function deleteTag(name){ const target=String(name||"").trim(); if(!target) return {ok:false,error:"标签不存在。"}; const before=state.tagLibrary.length; state.tagLibrary=state.tagLibrary.filter(function(tag){return tag.toLowerCase()!==target.toLowerCase();}); let todosChanged=false; const now=Date.now(); state.todos=state.todos.map(function(todo){ const nextTags=(todo.tags||[]).filter(function(tag){return tag.toLowerCase()!==target.toLowerCase();}); if(nextTags.length!==(todo.tags||[]).length){ todosChanged=true; return Object.assign({},todo,{tags:nextTags,updatedAt:now}); } return todo; }); if(state.settings.activeTag&&state.settings.activeTag.toLowerCase()===target.toLowerCase()){ state.settings.activeTag=""; await persistSettings(); } await persistTagLibrary(); if(todosChanged) await db.putTodos(state.todos); emit(); return {ok:true,removedFromLibrary:before!==state.tagLibrary.length,todosChanged:todosChanged}; }
    async function renameTag(oldName,newName){ const from=String(oldName||"").trim(); const toTags=normalizeTags(newName); if(!from||!toTags.length) return {ok:false,error:"标签名无效。"}; const to=toTags[0]; if(!(from.toLowerCase()===to.toLowerCase()&&from!==to)){ if(state.tagLibrary.some(function(tag){ return tag.toLowerCase()===to.toLowerCase()&&tag.toLowerCase()!==from.toLowerCase(); })) return {ok:false,error:"目标标签已存在。"}; } state.tagLibrary=uniqueTags(state.tagLibrary.map(function(tag){ return tag.toLowerCase()===from.toLowerCase()?to:tag; })).sort(function(a,b){return a.localeCompare(b,"zh-CN");}); const now=Date.now(); state.todos=state.todos.map(function(todo){ let changed=false; const nextTags=(todo.tags||[]).map(function(tag){ if(tag.toLowerCase()===from.toLowerCase()){ changed=true; return to; } return tag; }); if(!changed) return todo; return Object.assign({},todo,{tags:uniqueTags(nextTags),updatedAt:now}); }); if(state.settings.activeTag&&state.settings.activeTag.toLowerCase()===from.toLowerCase()){ state.settings.activeTag=to; await persistSettings(); } await persistTagLibrary(); await db.putTodos(state.todos); emit(); return {ok:true,tag:to}; }
    function createSharePack(){ return {version:2,type:"nova-todo-share",exportedAt:new Date().toISOString(),todos:state.todos,lists:state.lists,tagLibrary:state.tagLibrary,settings:{theme:state.settings.theme}}; }
    return {init:init,subscribe:subscribe,getSnapshot:getSnapshot,addTodo:addTodo,updateTodo:updateTodo,toggleTodo:toggleTodo,deleteTodo:deleteTodo,archiveTodo:archiveTodo,clearCompleted:clearCompleted,setSettings:setSettings,createList:createList,renameList:renameList,deleteList:deleteList,reorderVisible:reorderVisible,exportData:exportData,importData:importData,createTag:createTag,deleteTag:deleteTag,renameTag:renameTag,checkReminders:checkReminders,startReminderLoop:startReminderLoop,stopReminderLoop:stopReminderLoop,createSharePack:createSharePack,viewLabels:VIEW_LABELS,todayKey:todayKey,normalizeTags:normalizeTags,tagColor:tagColor,nextDueDate:nextDueDate,priorityRank:PRIORITY_RANK};
  }
  global.NovaStore={createStore:createStore,normalizeTodo:normalizeTodo,defaultSettings:defaultSettings,defaultLists:defaultLists,todayKey:todayKey,tagColor:tagColor,nextDueDate:nextDueDate};
})(window);
